from selenium.webdriver.common.by import By


class BasePageLocators:
    LOGO = (By.CSS_SELECTOR, 'a.logo')
    MEGA_MENU_CATEGORY = (By.CSS_SELECTOR, '.navigation__item')
    ACCEPT_ALL_COOKIES_BTN = (By.CSS_SELECTOR, 'button.coi-banner__accept')
    PROFILE_ICON = (By.CSS_SELECTOR, 'a.commerce-links__profile-icon')
    STORE_FINDER_ICON = (By.CSS_SELECTOR, 'a.commerce-links__storefinder')
    FAVORITES_ICON = (By.CSS_SELECTOR, '.favourites__icon')
    FAVOURITES_ICON_COUNT = (By.CSS_SELECTOR, '#favouritesCount')
    BASKET_ICON = (By.CSS_SELECTOR, '#basket_icon')
    BASKET_ICON_COUNT = (By.CSS_SELECTOR, 'span.basket__items-count')
    SEARCH_ICON = (By.CSS_SELECTOR, '.search-icon')
    RECENTLY_VIEWED_PRODUCT = (
        By.CSS_SELECTOR,
        '[data-list-name="Ribbon - Recently viewed products"] .product-item__content'
    )
    CCC = (By.XPATH, '(//*[@aria-label="Previous slide"])[3]')
    # GLOBAL SEARCH
    SEARCH_FIELD = (By.CSS_SELECTOR, '#global_search')
    GLOBAL_SEARCH_SHOW_ALL_BTN = (By.CSS_SELECTOR, '#showAllSearchResultsButton')
    NO_PRODUCTS_MSG = (By.CSS_SELECTOR, 'h3.no_results')
    CLOSE_SEARCH_ICON = (By.CSS_SELECTOR, '.close-icon')


class RegistrationPageLocators:
    FIRST_NAME_FIELD = (By.CSS_SELECTOR, '#FirstName')
    LAST_NAME_FIELD = (By.CSS_SELECTOR, '#LastName')
    EMAIL_FIELD = (By.CSS_SELECTOR, '#Email')
    PASSWORD_FIELD = (By.CSS_SELECTOR, '#Password')
    CONFIRM_PASSWORD_FIELD = (By.CSS_SELECTOR, '#ConfirmPassword')
    GENDER_FEMALE = (By.CSS_SELECTOR, '[for="GenderFemale"]')
    GENDER_MALE = (By.CSS_SELECTOR, '[for="GenderMale"]')
    ACCEPT_TERMS = (By.CSS_SELECTOR, '[for="AcceptConsent"]')
    ACCEPT_TERMS_LINK = (By.CSS_SELECTOR, '[for="AcceptConsent"] a')
    CREATE_ACCOUNT_BTN = (By.CSS_SELECTOR, '.ecco_button__center')
    FIRST_NAME_ERROR = (By.CSS_SELECTOR, '#FirstName-error')
    LAST_NAME_ERROR = (By.CSS_SELECTOR, '#LastName-error')
    EMAIL_ERROR = (By.CSS_SELECTOR, '#Email-error')
    PASSWORD_ERROR = (By.CSS_SELECTOR, '#Password-error')
    CONFIRM_PASSWORD_ERROR = (By.CSS_SELECTOR, '#ConfirmPassword-error')
    ACCEPT_TERMS_ERROR = (By.CSS_SELECTOR, '#AcceptConsent-error')
    TERMS_WINDOW_ELEMENT = (By.CSS_SELECTOR, '.signup-consent-dialog')


class LoginPageLocators:
    EMAIL_FIELD = (By.CSS_SELECTOR, '#Email')
    PASSWORD_FIELD = (By.CSS_SELECTOR, '#Password')
    SHOW_PASSWORD_BTN = (By.CSS_SELECTOR, '.showpass')
    HIDE_PASSWORD_BTN = (By.CSS_SELECTOR, '.hidepass')
    FORGOT_PASSWORD_LINK = (By.CSS_SELECTOR, '.forgot-password')
    SIGN_IN_BTN = (By.CSS_SELECTOR, '.myecco-auth-box-btn-container>[type="submit"]')
    CREATE_ACCOUNT_BTN = (By.CSS_SELECTOR, '#createCustomerArea a')
    EMAIL_ERROR = (By.CSS_SELECTOR, '#Email-error')
    PASSWORD_ERROR = (By.CSS_SELECTOR, '#Password-error')
    LOGIN_ERROR = (By.CSS_SELECTOR, '[data-valmsg-for="Invalid Login"]')


class AccountPageLocators:
    GREETING_TITLE = (By.CSS_SELECTOR, '.myecco-overview-greeting>.heading')
    SEE_DETAILS_LINK = (By.XPATH, '//*[.="See details"]')
    SEE_ORDERS_LINK = (By.XPATH, '//*[.="See orders"]')
    GO_TO_MY_FAVORITES_LINK = (By.XPATH, '//*[.="Go to my favorites"]')
    SEE_SUBSCRIPTIONS_LINK = (By.XPATH, '//*[.="See subscriptions"]')
    SELECT_MY_STORE_LINK = (By.XPATH, '// *[. = "SELECT MY STORE"]')
    SIGH_OUT_BTN = (By.CSS_SELECTOR, '.login-signup .logoff__button')
    # SIDE MENU LINKS
    TO_MY_ECCO_LINK = (By.CSS_SELECTOR, '.goback-link')
    MY_PERSONAL_DETAILS_LINK = (By.CSS_SELECTOR, '//a[.="My Personal Details"]')
    MY_ORDERS_LINK = (By.XPATH, '//a[.="My Orders"]')
    MY_FAVOURITES_LINK = (By.XPATH, '//a[.="MY FAVOURITES"]')
    MY_SUBSCRIPTIONS_LINK = (By.XPATH, '//a[.="MY SUBSCRIPTIONS"]')
    # PERSONAL DETAILS PAGE
    USER_NAME = (By.CSS_SELECTOR, '#AccountDetailsID>p:nth-child(2)')
    # EDIT PAGE
    FIRST_NAME_FIELD = (By.CSS_SELECTOR, '#FirstName')
    LAST_NAME_FIELD = (By.CSS_SELECTOR, '#LastName')
    EMAIL_FIELD = (By.CSS_SELECTOR, '#Email')
    PHONE_NUMBER_FIELD = (By.CSS_SELECTOR, '#PhoneNumber')
    DAY_PICKER = (By.CSS_SELECTOR, '#myecco-profile-date-picker__date')
    MONTH_PICKER = (By.CSS_SELECTOR, '#myecco-profile-date-picker__month')
    YEAR_PICKER = (By.CSS_SELECTOR, '#myecco-profile-date-picker__year')
    YEAR_PICKER_CLOSE_ICON = (By.CSS_SELECTOR, '#myecco-profile-date-picker__close-icon')
    DAY_TO_CHOOSE = (By.CSS_SELECTOR, '.day')
    MONTH_TO_CHOOSE = (By.CSS_SELECTOR, '.month')
    YEAR_TO_CHOOSE = (By.CSS_SELECTOR, '.year')
    YEAR_TO_CHOOSE_SELECTED = (By.CSS_SELECTOR, '.year.selected')
    CLEAR_DATE_LINK = (By.CSS_SELECTOR, '.label-input-group .underlined-link.date-picker__clear-all-btn')
    SAVE_USER_DETAILS_BTN = (By.CSS_SELECTOR, '.ecco_button__center .ecco_button--fullwidth')
    FIRST_NAME_ERROR = (By.CSS_SELECTOR, '#FirstName-error')
    LAST_NAME_ERROR = (By.CSS_SELECTOR, '#LastName-error')
    EMAIL_ERROR = (By.CSS_SELECTOR, '#Email-error')
    PHONE_NUMBER_ERROR = (By.CSS_SELECTOR, '#PhoneNumber-error')
    UPDATED_USER_INFO_TEXT = (By.CSS_SELECTOR, '#form0 .info-text')
    # FAVOURITE PAGE
    MY_FAVOURITES_TITLE = (By.CSS_SELECTOR, '.heading--h1')
    PRODUCT_NAME = (By.CSS_SELECTOR, '.product_name')
    PRODUCT_PRICE = (By.CSS_SELECTOR, '.price')
    PRODUCT_COLOR = (By.CSS_SELECTOR, '.product_color')
    DELETE_FAVOURITE_BTN = (By.CSS_SELECTOR, '[data-title="Delete favourite"]')
    DELETE_FAVOURITE_OK_BUTTON = (By.CSS_SELECTOR, '.modal__ok')
    SHARE_FAVOURITES_BTN = (By.CSS_SELECTOR, '.accordion__title')
    EMPTY_FAVORITES_MSG = (By.CSS_SELECTOR, '.myecco-favourite__messages')
    SIGN_IN_BTN = (By.XPATH, '//*[.="Sign in now"]')
    COPY_LINK_FIELD = (By.CSS_SELECTOR, 'input#copylink')
    # EDIT BILLING ADDRESS PAGE
    BILLING_ADDRESS_FIRST_NAME_FIELD = (By.CSS_SELECTOR, '#FirstName')
    BILLING_ADDRESS_LAST_NAME_FIELD = (By.CSS_SELECTOR, '#LastName')
    BILLING_ADDRESS_STREET_FIELD = (By.CSS_SELECTOR, '#Street')
    BILLING_ADDRESS_NUMBER_FIELD = (By.CSS_SELECTOR, '#Number')
    BILLING_ADDRESS_POST_CODE_FIELD = (By.CSS_SELECTOR, '#ZipCode')
    BILLING_ADDRESS_CITY_FIELD = (By.CSS_SELECTOR, '#City')
    BILLING_ADDRESS_SAVE_BTN = (By.XPATH, '//button[contains(text(), "SAVE ADDRESS")]')
    STREET_ERROR = (By.CSS_SELECTOR, '#Street-error')
    HOUSE_NUMBER_ERROR = (By.CSS_SELECTOR, '#Number-error')
    POST_CODE_ERROR = (By.CSS_SELECTOR, '#ZipCode-error')
    CITY_ERROR = (By.CSS_SELECTOR, '#City-error')
    # ADDRESS BOOK PAGE
    ADDRESS_BOOK_STREET = (By.CSS_SELECTOR, '.col-sm-12:nth-child(1)>p:nth-child(3)')
    ADDRESS_BOOK_CITY = (By.CSS_SELECTOR, '.col-sm-12:nth-child(1)>p:nth-child(4)')
    ADD_ADDRESS_BTN = (By.XPATH, '//*[.="Add address"]')
    EDIT_ADDRESS_LINK = (By.CSS_SELECTOR, '.edit')
    DELETE_ADDRESS_BTN = (By.CSS_SELECTOR, '.delete')
    DELETE_ADDRESS_OK_BUTTON = (By.CSS_SELECTOR, '.modal__ok')
    NO_ADDRESS_MSG = (By.CSS_SELECTOR, '.myecco-address-book__addresses p')


class ProductPageLocators:
    ADD_TO_BASKET_BTN = (By.CSS_SELECTOR, '.product_info__buttons-primary')
    CLICK_AND_COLLECT_BTN = (By.CSS_SELECTOR, '.product_info__buttons-secondary')
    ADD_TO_FAVORITES_BTN = (By.CSS_SELECTOR, '.product_info__add-to-wishlist')
    ADD_TO_FAVORITES_TOOLTIP = (By.CSS_SELECTOR, '.tooltip__content')
    PRODUCT_TITLE = (By.CSS_SELECTOR, '.product_info__intro-title')
    PRODUCT_PRICE = (By.CSS_SELECTOR, '.product_info__price')
    PRODUCT_COLOR = (By.CSS_SELECTOR, '.product_info__color--selected')
    COLOR_SELECTOR_ITEM = (By.CSS_SELECTOR, '.product_info__color-item')
    PRODUCT_IMAGE = (By.CSS_SELECTOR, '.product_details__media-item-img img')
    AVAILABLE_SIZE = (By.CSS_SELECTOR, '.size-picker__item[title=""]')
    SIZE_GUIDE_BTN = (By.CSS_SELECTOR, 'button.size-guide-button')
    SIZE_GUIDE_MODAL = (By.CSS_SELECTOR, '.modal__inner-wrapper--size-guide')
    SIZE_GUIDE_ADD_SIZE_BTN = (By.CSS_SELECTOR, '.size-guide__calculator .shown')
    MINI_BASKET_OVERLAY = (By.CSS_SELECTOR, '.basket_overlay__wrapper--visible')
    MINI_BASKET_GO_TO_BASKET_BTN = (By.CSS_SELECTOR, '.basket_overlay__wrapper--visible a.ecco_button')
    MINI_BASKET_KEEP_SHOPPING_BTN = (By.CSS_SELECTOR, '.basket_overlay__wrapper--visible [aria-label="Keep Shopping"]')
    MINI_BASKET_PRODUCT_TITLE = (By.CSS_SELECTOR, '.basket_overlay__wrapper--visible .product_name')
    MINI_BASKET_PRODUCT_COLOR = (By.CSS_SELECTOR, '.basket_overlay__wrapper--visible .product_color')
    MINI_BASKET_PRODUCT_SIZE = (
        By.CSS_SELECTOR, '.basket_overlay__wrapper--visible .product_size .product_size__variant'
    )
    MINI_BASKET_PRODUCT_PRICE = (By.CSS_SELECTOR, '.basket_overlay__wrapper--visible .price')
    MINI_BASKET_TOTAL = (By.CSS_SELECTOR, '.basket_overlay__wrapper--visible .summary_total .summary_price')
    MINI_BASKET_NUMBER_OF_ITEMS = (By.CSS_SELECTOR, '.basket_overlay__wrapper--visible .summary_num-of-items')


class PLPLocators:
    FILTERS_ITEMS_COUNT = (By.CSS_SELECTOR, '.count-indicator')
    FILTERS_COLOR = (By.CSS_SELECTOR, '#dominantcolor')
    FILTERS_COLOR_NAME = (By.CSS_SELECTOR, '#dominantcolor .custom_selectbox__list-item-checkbox')
    FILTERS_COLOR_AMOUNT = (By.CSS_SELECTOR, '#dominantcolor .amount')
    FILTERS_PRICE = (By.CSS_SELECTOR, '.filter-btn #adjustedprice')
    SELECTED_FILTER = (By.CSS_SELECTOR, '.selected-filter')
    SORT_BY_DROPDOWN = (By.CSS_SELECTOR, '.filters-sorting__container')
    SORT_BY_PRICE_ASC = (By.XPATH, '//*[.="Lowest price"]/..')
    SORT_BY_PRICE_DESC = (By.XPATH, '//*[.="Highest price"]/..')
    PRICE_SLIDER_MIN = (By.CSS_SELECTOR, '.handle-left')
    PRICE_SLIDER_MAX = (By.CSS_SELECTOR, '.handle-right')
    PRICE_RANGE_MIN = (By.CSS_SELECTOR, '.rangeslider__value--min')
    PRICE_RANGE_MAX = (By.CSS_SELECTOR, '.rangeslider__value--max')
    CLEAR_ALL_BTN = (By.CSS_SELECTOR, '.selected-filter.clear-filters-btn')
    PRODUCT_PRICE = (By.CSS_SELECTOR, '.meta__price')
    PRODUCT_TITLE = (By.CSS_SELECTOR, '.meta__title')
    ADD_TO_FAVORITE_ICON = (By.CSS_SELECTOR, '#favorite-fill')
    BACK_TO_TOP_BTN = (By.CSS_SELECTOR, '.scroll-to-top')


class BasketPageLocators:
    PRODUCT_NAME = (By.CSS_SELECTOR, '.product_name')
    PRODUCT_COLOR = (By.CSS_SELECTOR, '.product_color')
    PRODUCT_SIZE = (By.CSS_SELECTOR, '.product_size__variant')
    PRODUCT_PRICE = (By.CSS_SELECTOR, 'p.price')
    LOWER_CHECKOUT_BTN = (By.CSS_SELECTOR, '.checkoutsf_nav--bottom .ecco_button--check-out')
    VOUCHER_CODE_FIELD = (By.CSS_SELECTOR, '.checkoutsf_basket_voucher__apply__body input')
    REDEEM_CODE = (By.CSS_SELECTOR, '.checkoutsf_basket_voucher__apply__body .ecco_button')
    DELETE_BTN = (By.CSS_SELECTOR, '.delete_btn')
    CLICK_AND_COLLECT_RADIO_BTN = (By.XPATH, '//*[.="Click & Collect"]')
    TOTAL_PRICE = (By.CSS_SELECTOR, '.checkoutsf_totalprices__price:nth-child(6) span')
    CHOOSE_STORE_BTN = (By.CSS_SELECTOR, '.my-store button')
    SELECT_STORE_BTN = (By.CSS_SELECTOR, '.selectStoreButton')
    STORE_NAME = (By.CSS_SELECTOR, '.my-pickup-store h4')
    STORE_LOCATOR_STORE_NAME = (By.CSS_SELECTOR, '.store-locator__stores-list h5')
    VOUCHER_CODE_ERROR = (By.CSS_SELECTOR, '.checkoutsf_basket_voucher__error')
    EMPTY_BASKET_MSG = (By.CSS_SELECTOR, '.checkoutsf_basket__basket-message h2')
    CONTINUE_SHOPPING_BTN = (By.CSS_SELECTOR, '.checkoutsf_basket__basket-message a')


class CheckoutDeliveryPageLocators:
    BILLING_ADDRESS_FIRST_NAME_FIELD = (By.CSS_SELECTOR, '#BillingAddress_FirstName')
    BILLING_ADDRESS_LAST_NAME_FIELD = (By.CSS_SELECTOR, '#BillingAddress_LastName')
    BILLING_ADDRESS_STREET_FIELD = (By.CSS_SELECTOR, '#BillingAddress_Street')
    BILLING_ADDRESS_NUMBER_FIELD = (By.CSS_SELECTOR, '#BillingAddress_StreetNumber')
    BILLING_ADDRESS_POST_CODE_FIELD = (By.CSS_SELECTOR, '#BillingAddress_ZipCode')
    BILLING_ADDRESS_CITY_FIELD = (By.CSS_SELECTOR, '#BillingAddress_City')
    PHONE_NUMBER_FIELD = (By.CSS_SELECTOR, '#PersonalInfo_PhoneNumber')
    GO_TO_SUMMARY_BTN = (By.CSS_SELECTOR, '.ecco_button--check-out')
    GO_TO_BASKET_LINK = (By.CSS_SELECTOR, '.checkoutsf_delivery-page__other-delivery-option a')
    BILLING_STREET_ERROR = (By.CSS_SELECTOR, '#BillingAddress_Street-error')
    BILLING_NUMBER_ERROR = (By.CSS_SELECTOR, '#BillingAddress_StreetNumber-error')
    BILLING_POST_CODE_ERROR = (By.CSS_SELECTOR, '#BillingAddress_ZipCode-error')
    BILLING_CITY_ERROR = (By.CSS_SELECTOR, '#BillingAddress_City-error')
    TERMS_AND_CONDITIONS_LINK = (By.CSS_SELECTOR, '.label-input__label--required [type="ConsentContent"]:nth-child(2)')
    ACCEPT_PRIVACY_POLICY_LINK = (By.CSS_SELECTOR, '.ecco-checkbox__dialog-link:nth-child(4)')
    CONSENT_MODAL = (By.CSS_SELECTOR, 'section .modal__inner-wrapper')
    CLOSE_CONSENT_MODAL_ICON = (By.CSS_SELECTOR, 'section .modal__inner-wrapper .modal__close')
    CONSENT_MODAL_TITLE = (By.CSS_SELECTOR, 'section .modal__inner-wrapper h1')
    ACCEPT_TERMS_CHECKBOX = (By.CSS_SELECTOR, '.terms-condition-text:nth-child(1)')
    ACCEPT_CONSENT_ERROR = (By.CSS_SELECTOR, '#AcceptCheckoutConsent-error')


class CheckoutSummaryPageLocators:
    PRODUCT_NAME = BasketPageLocators.PRODUCT_NAME
    PRODUCT_COLOR = BasketPageLocators.PRODUCT_COLOR
    PRODUCT_SIZE = BasketPageLocators.PRODUCT_SIZE
    PRODUCT_PRICE = BasketPageLocators.PRODUCT_PRICE
    TOTAL_PRICE = (By.XPATH, '//p[contains(text(), "Total")]//span')
    CHANGE_ADDRESS_LINK = (By.CSS_SELECTOR, '.checkoutsf_summary__info__link a')
    GO_TO_PAYMENT_BTN = (By.CSS_SELECTOR, '.small-space .ecco_button--check-out-steps-summary')
    BILLING_ADDRESS = (By.XPATH, '// *[contains(text(), "Billing")] /../ p[2]')
    BILLING_POST_CODE = (By.XPATH, '//*[contains(text(), "Billing")]/../p[3]')
    CARD_PAYMENT_METHOD = (By.CSS_SELECTOR, '[data-method="PayCard"]')
